### ISSUE TITLE
[BA2250 > Volunteering in BA2250] Clarify what "outside of these [standard 8am-9pm] hours" means on the Volunteering page for future reference.

### ISSUE THREAD

**Issue by dannychen27** [cssu/cssu.ca#30]
"Members of the Executive Council shall have access outside of these hours to the lounge (BA2250) and storage room (BA2285)."

Someone asks, "Do execs get 24/7 lounge access (excluding UofT holidays)?"
An exec wrote, "not sure, i think so"

Could a current exec or past exec please clarify (including a screenshot of exec's quote, or paraphrased response) whether "outside of standard hours" imply 24/7 lounge access, excluding UofT holidays and other closures?

Cheers :D

**Comment by ff-zhang** [comment]
Execs are supposed to have 24/7 lounge access except when Bahen itself is closed. This is not always the case, especially early in the semester, but I believe all the execs have 24/7 access right now.
